config/routes.rb
Rails.application.routes.draw do
  resources :shorted_urls
  root to: 'shorted_urls#new'
  get  '/shorted_urls/fetch_origin_url'
  get "/shorted_urls/url_stat"

end

app/models/stored_url.rb
class StoredUrl < ActiveRecord::Base
  SHORT_URL_LENGTH = 7

  has_many :url_infos
  validates :original_url, presence: true, on: :create
  validates_format_of :original_url, with: /\A(https?:\/\/)?([\da-z\.-]+)\.([a-z\.]{2,6})([\/\w\.-]*)*\/?\Z/i
  
  before_create :crerate_optimize_url
  before_create :cleaning_url

  def crerate_optimize_url
    #creating the random 7 char short url
  	#new_url = Random.new.bytes(6) + rand(100..10000).to_s
  	new_url = ([*('a'..'z'),*('0'..'9')]).sample(SHORT_URL_LENGTH).join
  	old_url = StoredUrl.where(short_url: new_url).last
  	if old_url.present?
  		self.crerate_optimize_url
  	else
  		self.short_url = new_url
  	end
  end

  def duplicate_url
  	StoredUrl.find_by_purify_url(self.purify_url)
  end

  def new_url?
  	duplicate_url.nil?
  end

  def cleaning_url
  	self.original_url.strip
    #cleaning and filtering the real url
  	#self.purify_url = self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")
  	self.purify_url = "http://#{self.original_url.downcase.gsub(/(https?:\/\/)|(www\.)/, "")}"
  end





end

app/models/url_info.rb
class UrlInfo < ActiveRecord::Base
 belongs_to :short_url
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/shorted_urls_controller.rb
class ShortedUrlsController < ApplicationController

	before_action :search_url, only: [:show, :clear]
	skip_before_filter :verify_authenticity_token

	def index
		@urls = StoredUrl.all
	end

	def new
		@url = StoredUrl.new
	end

	def show
		@url = StoredUrl.find_by_id(params[:id])
		if @url.present?
			@url_host = request.remote_ip
		   GetStat.new(@url_host, browser, @url).call
		end
	end

	def url_stat
  		@url = StoredUrl.find_by_id(params[:id])
    end

	def create
		@url = StoredUrl.new(url_params)
		@url.cleaning_url
		if @url.new_url?
			if @url.save
				#redirect_to shorted_urls_path(@url.short_url)
				redirect_to shorted_urls_path
			else
				flash[:error] = "somethis wrong here"
				render "new"
			end
		else
			flash[:notice] = "shortend url  already present in your database"
			#redirect_to shorted_url_path(@url.duplicate_urls.short_url)
			redirect_to shorted_urls_path
	    end		

	end

	def clear
		@url = search_url
		host = request.host_with_port
		@original_url = @url.purify_url
		@short_url = host + '/' + @url.short_url
	end

	def fet_origin_url
		fetch_url = search_url
		redirect_to fetch_url.purify_url
	end

	private


	def search_url
		@url = StoredUrl.find_by_short_url(params[:short_url])
	end

	def url_params
    	params.permit(:original_url)
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/shorted_urls_helper.rb
module ShortedUrlsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>UrlShortenerApp</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/shorted_urls/clear.html.erb
<html>
   <body>
	  <center>
	  	<h2> Original URl : <%= @original_url %></h2>
	  	<h2> shortend URl : <%= @short_url %></h2>
	  </center>
   </body>
 </html>

app/views/shorted_urls/index.html.erb
<head>
  <title>ALL URLS</title>
</head>
<body>
	<center>
  		<h2>ALL URLS</h1>
  		<p><%= link_to "Create short url", root_path %></p>
  	</center>
  <table style="width:100%">
<th>ID</th>
<th>Original Url</th>
<th>Short Url </th>
<th>Count Of View </th>
<% @urls.each do |u| %>
<tr align = "center">
	<td><%= u.id %></td>
  <td><%= u.original_url %></td>
	<td><%= u.short_url %></td>
  <td><%= u.url_infos.count %></td>
	<td><button><%= link_to "CHECK", shorted_url_path(id: u.id) %></button></td>
</tr>
<% end %>
</table>
</body>

app/views/shorted_urls/new.html.erb
<html>
   <body>
	  <center>
	  	<h2> Enter The URL</h2>
	  	<form action = "shorted_urls", method = "post">
	  	  <input type = "text",  value = "", name = "original_url" />
	  	  <input type= "submit",  value = "Submit"> 
	    </form>
	    <h2> VIEW ALL The URLS</h2>
	    <p><%= link_to "check all data", shorted_urls_path %></p>
	  </center>
   </body>
 </html>

app/views/shorted_urls/show.html.erb
</head>
<body>
	<center>
  		<h1>Statistics</h1>
  		<p><%= link_to "Create short url", new_shorted_url_path %></p>
      <p><%= link_to "List of url", shorted_urls_path %></p>
  	</center>
  <table style="width:100%">
<th>ID</th>
<th>Original Url</th>
<th>Short Url </th>
<th>Total views </th>
<tr align = "center">
	<td><%= @url.id %></td>
	<td><%= @url.original_url %></td>
  <td><a href=/u/<%= @url.short_url %>>https://<%= request.host %>/u/<%= @url.short_url %></a></td>
	<td><%= @url.url_infos.count %></td>
</tr>
</table>
<p> </p>
<p> </p>
<table style="width:100%">
  <th>Sr.no</th>
  <th>User IP</th>
  <th>View at</th>
  <th>Browser Info</th>
  <th>Browser platform</th>
  <% @url.url_infos.each_with_index do |u, index| %>
    <tr>
      <td><%= index +1 %></td>
       <td><%= u.host %></td>
      <td><%= u.created_at %></td>
      <td><%= u.browser_info %></td>
      <td><%= u.browser_platform %></td>
      </tr>
  <% end %>
</table>
</body>